### ISSUE TITLE
Docker: allow setting time zone 

### ISSUE THREAD

**Issue by d3mystified** [jl94x4/ColleXions#13]
`TZ` env var should be respected so date based collections can be accurately accounted for.

linuxserver images do this, so that can be a good starting point for implementing

**Comment by jl94x4** [comment]
It should already use the local time of the device that it's ran from? Is that not the case for you?

**Comment by jl94x4** [comment]
Just pushed an update to the latest branch with timezone variables

Example ```-e TZ="Europe/London"```
