### ISSUE TITLE
Add sleep for interval

### ISSUE THREAD

**Issue by d3mystified** [jl94x4/ColleXions#3]
I don't see a sleep here:

https://github.com/jl94x4/ColleXions/blob/955e95b8563a2d955d4d437d0870d4fb0169f5cd/ColleXions.py#L274

The code reads the `pinning_interval` and then converts it to seconds https://github.com/jl94x4/ColleXions/blob/955e95b8563a2d955d4d437d0870d4fb0169f5cd/ColleXions.py#L231 but doesn't actually use it. Probably should do a sleep instead of doing an exit, no?

**Comment by jl94x4** [comment]
This is fixed in [v1.12](https://github.com/jl94x4/ColleXions/releases/latest)
